name: Build Electron App for macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Aggiunge il pulsante per avviare manualmente il workflow

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the Electron app for macOS
      - name: Build Electron app
        run: npm run package

      - name: Create tag
        id: tag_step
        run: |
          TAG_NAME=v1.0.$(date +'%Y%m%d%H%M%S')
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/build/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
